### ISSUE TITLE
Integration of MorphStore operators

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#231]
In GitLab by @EricMier on Mar 21, 2022, 16:52

### Goals
Enable the use of existing data processing operators of [MorphStore](https://morphstore.github.io/), an in-memory columnar analytical query engine with a novel holistic compression-enabeld and highly-vectorized processing model.

### Tasks
- [ ] Add MorphStore as a new library
- [ ] Create Daphne Kernels using MorphStore operators (wrapper + data format translation)
- [ ] Create some test cases

More Information will follow.

**Comment by EricMier** [comment]
Moved to #339.
