### ISSUE TITLE
Integration of MorphStore operators

### ISSUE THREAD

**Issue by EricMier** [daphne-eu/daphne#339]
### Goals
Enable the use of existing data processing operators of [MorphStore](https://morphstore.github.io/), an in-memory columnar analytical query engine with a novel holistic compression-enabeld and highly-vectorized processing model.

### Tasks
- [ ] Add MorphStore as a new library
- [ ] Create Daphne Kernels using MorphStore operators (wrapper + data format translation)
- [ ] Create some test cases

More Information will follow.

**Comment by tomschw** [comment]
I would like to work on this issue.
